


spring:
  application:
    name: home
  datasource:
    driver-class-name:  oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: SPRING_BOOT
    PASSWORD: SPRING_BOOT_1234


mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:home/**/dao/mapper/*DaoMapper.xml
